name: responsive_counter
description: Flutter Responsive Counter
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: 3.16.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true